[versions]
kotlin = "2.0.21"
junit = "4.13.2"
kotlinx-io = "0.6.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-io = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }

[plugins]
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }